# Zsh
autoload -U promptinit; promptinit
prompt pure
# End Zsh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
chruby 2.5.3

# Alias
alias be="bundle exec"
alias rails_next="SHOPIFY_NEXT=1 DISABLE_SPRING=1 $@"
# End Alias
